### ISSUE TITLE
woz build fails on new app

### ISSUE THREAD

**Issue by tinywombat765** [alexkehayias/woz#4]
Running woz build and the new app created by woz new fails with the error `Missing identity ID in cache`.

System: Linux
woz: 1.3.0 musl

**Comment by alexkehayias** [comment]
Looks like the build command is still doing pre-flight checks for your account, but you probably haven’t signed up so to fix it run ‘woz signup’ (it’s free). For context, woz uses AWS Cognito to give you auth/identity for the free hosting service which makes it considerably easier to play around due to the PWA https requirement.  

However, we really should allow you to build without an account that way you can host the static files how you want so to close this issue I can decouple those two things and update the docs.

**Comment by alexkehayias** [comment]
@zethra I just pushed v1.3.1 https://github.com/alexkehayias/woz/releases/tag/v1.3.1 which decouples the need to have an account from the `build` command. I've also update the readme and docs.

To install the latest version 

```sh
curl -LSfs https://woz.sh/bin/install.sh | sh -s -- -f --target x86_64-unknown-linux-musl
```

Let me know if that unblocks you from doing what you are trying to do.

**Comment by alexkehayias** [comment]
Closing this since it's now possible to run the build command without an account.
